// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSuEvNsZWQeVpuz3HpQAnaHVNfWP-e71o',
    appId: '1:698961663941:web:da2d4c3381f6390634ddac',
    messagingSenderId: '698961663941',
    projectId: 'flutter-9d03e',
    authDomain: 'flutter-9d03e.firebaseapp.com',
    storageBucket: 'flutter-9d03e.appspot.com',
    measurementId: 'G-CSD0V7X2DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA39Z0BMvALTWL-IMjLcgCskV4J2AHrFEY',
    appId: '1:698961663941:android:1636af30f04cadf734ddac',
    messagingSenderId: '698961663941',
    projectId: 'flutter-9d03e',
    storageBucket: 'flutter-9d03e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-f0qJzACY9tfRo9hG4SG3Bs85nV-w1dE',
    appId: '1:698961663941:ios:8c0d55311d86f65f34ddac',
    messagingSenderId: '698961663941',
    projectId: 'flutter-9d03e',
    storageBucket: 'flutter-9d03e.appspot.com',
    iosBundleId: 'com.example.hookInfinitelist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-f0qJzACY9tfRo9hG4SG3Bs85nV-w1dE',
    appId: '1:698961663941:ios:82b93eb806048efe34ddac',
    messagingSenderId: '698961663941',
    projectId: 'flutter-9d03e',
    storageBucket: 'flutter-9d03e.appspot.com',
    iosBundleId: 'com.example.hookInfinitelist.RunnerTests',
  );
}
